databases:
  - name: easebackenddb
    plan: free
    databaseName: easebackenddb
    user: easebackenddb_user

services:
  - type: web
    plan: free
    name: Easebackend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn core.wsgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: easebackenddb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4